### Create event

POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "NLW Unite",
  "details": null,
  "maximumAttendees": 1
}

### Register attendee on event

POST http://localhost:3333/events/7f4b2405-2589-43b4-b125-0ee90fce9f9f/register
Content-Type: application/json

{
  "name": "Adrian Mouzinho",
  "email": "adrianmouzinho2@example.com"
}

### Get event

GET http://localhost:3333/events/abce242c-fe72-4cf8-9804-9a0dfe1df2b4
